#!/usr/bin/env python3
"""Generate resources/source_jobs.yml from sources.yml for bundle deployment.

Each source entry in sources.yml that has `deploy_job: true` gets its own
Databricks job created in the bundle. Run automatically by `make bundle-deploy`.

Usage:
    python scripts/generate_source_jobs.py
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
SOURCES_YML = ROOT / "sources.yml"
OUTPUT_YML = ROOT / "resources" / "source_jobs.yml"

# Read version from version.txt so the wheel filename stays in sync
_raw_version = (ROOT / "version.txt").read_text().strip().lstrip("v")
WHL_FILENAME = f"agentic_datamodeling-{_raw_version}-py3-none-any.whl"
# ${workspace.root_path} resolves to the bundle root (e.g. /Workspace/Shared/hackathon/…/prod).
# Artifacts are always uploaded to root_path/artifacts/.internal/ — NOT root_path/files/.internal/
WHL_PATH = f"${{workspace.root_path}}/artifacts/.internal/{WHL_FILENAME}"

# Serverless environment key — used by all tasks in every generated job
ENV_KEY = "adm_env"


def _job_key(name: str) -> str:
    return f"discover_{name.lower().replace('-', '_').replace(' ', '_')}"


def _build_params(source: dict) -> list[str]:
    stype = source["type"]
    params: list[str] = ["--source", stype]

    if stype == "unity_catalog":
        if source.get("catalog"):
            params += ["--catalog", source["catalog"]]
        if source.get("schema"):
            params += ["--schema", source["schema"]]
        if source.get("warehouse_id"):
            params += ["--warehouse-id", source["warehouse_id"]]
    else:
        # JDBC: schema + connection string.
        # Databricks resolves {{secrets/scope/key}} in python_wheel_task.parameters
        # at job-run time — the secret scope/key must exist before running the job.
        if source.get("schema"):
            params += ["--schema", source["schema"]]
        if source.get("secret_scope") and source.get("secret_key"):
            scope = source["secret_scope"]
            key = source["secret_key"]
            params += ["--connection-string", f"{{{{secrets/{scope}/{key}}}}}"]
        elif source.get("connection_string"):
            params += ["--connection-string", source["connection_string"]]

    return params


def _build_job(source: dict) -> dict:
    name = source["name"]
    stype = source["type"]
    desc = source.get("description", f"Discover {name} ({stype})")

    return {
        "name": f"[${{bundle.target}}] Discover — {name}",
        "description": desc,
        # Serverless: wheel goes in environments.spec.dependencies, not task libraries.
        # Tasks reference the environment via environment_key; no job_cluster_key needed.
        "environments": [
            {
                "environment_key": ENV_KEY,
                "spec": {
                    "client": "1",
                    "dependencies": [WHL_PATH],
                },
            }
        ],
        "tasks": [
            {
                "task_key": "discover",
                "python_wheel_task": {
                    "package_name": "agentic-datamodeling",
                    "entry_point": "discover",
                    "parameters": _build_params(source),
                },
                "environment_key": ENV_KEY,
            }
        ],
        "permissions": [{"level": "CAN_VIEW", "group_name": "datamodeling_hackathon"}],
    }


def main() -> None:
    """Generate resources/source_jobs.yml from sources.yml."""
    if not SOURCES_YML.exists():
        print("sources.yml not found — skipping job generation.")
        if OUTPUT_YML.exists():
            OUTPUT_YML.unlink()
        return

    with open(SOURCES_YML) as f:
        data: dict = yaml.safe_load(f) or {}

    sources = data.get("sources", [])

    if not sources:
        print("No sources in sources.yml — nothing to generate.")
        if OUTPUT_YML.exists():
            OUTPUT_YML.unlink()
            print(f"Removed stale {OUTPUT_YML.name}")
        return

    jobs = {_job_key(s["name"]): _build_job(s) for s in sources}
    output = {"resources": {"jobs": jobs}}

    with open(OUTPUT_YML, "w") as f:
        f.write("# Auto-generated from sources.yml — do not edit manually.\n")
        f.write("# Regenerated by 'make generate-jobs' or 'make bundle-deploy'.\n\n")
        yaml.dump(output, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"Generated {len(jobs)} job(s) → {OUTPUT_YML.relative_to(ROOT)}")
    for key, job in jobs.items():
        print(f"  [{key}]  {job['name']}")


if __name__ == "__main__":
    main()
