"""Generate Databricks Unity Catalog DDL with PK/FK constraints from a discovery report."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Type mapping: source types → Databricks SQL types
# ---------------------------------------------------------------------------

_TYPE_MAP: dict[str, str] = {
    "bigint": "BIGINT",
    "int": "INT",
    "integer": "INT",
    "smallint": "SMALLINT",
    "tinyint": "TINYINT",
    "long": "BIGINT",
    "double": "DOUBLE",
    "float": "FLOAT",
    "decimal": "DECIMAL(18,2)",
    "numeric": "DECIMAL(18,2)",
    "string": "STRING",
    "varchar": "STRING",
    "char": "STRING",
    "text": "STRING",
    "boolean": "BOOLEAN",
    "bool": "BOOLEAN",
    "timestamp": "TIMESTAMP",
    "timestamp_ntz": "TIMESTAMP_NTZ",
    "date": "DATE",
    "binary": "BINARY",
    "array": "ARRAY<STRING>",
    "map": "MAP<STRING,STRING>",
    "struct": "STRUCT<>",
}

# MonthlyRent and similar currency columns get DECIMAL instead of BIGINT
_CURRENCY_COLUMNS = {"monthlyrent", "rent", "price", "amount", "cost", "fee", "balance"}


def _map_type(col_name: str, raw_type: str) -> str:
    """Map source type to Databricks SQL type, with currency-column overrides."""
    if col_name.lower().replace("_", "") in _CURRENCY_COLUMNS and raw_type.lower() == "bigint":
        return "DECIMAL(18,2)"
    base = raw_type.lower().split("(")[0].strip()
    return _TYPE_MAP.get(base, raw_type.upper())


# ---------------------------------------------------------------------------
# PK inference
# ---------------------------------------------------------------------------


def _infer_pk(table_name: str, columns: list[dict]) -> str | None:
    """Infer primary key column: prefer {TableName}ID, then ID, then first BIGINT."""
    col_names = [c["name"] for c in columns]
    candidates = [
        f"{table_name}ID",
        f"{table_name}Id",
        f"{table_name}_id",
        "ID",
        "Id",
        "id",
        "SNO",
    ]
    for candidate in candidates:
        if candidate in col_names:
            return candidate
    # fall back to first bigint/int column
    for col in columns:
        if col["type"].lower() in ("bigint", "int", "integer", "long"):
            return col["name"]
    return col_names[0] if col_names else None


def _resolve_parent_column(parent_table: str, parent_col_hint: str, tables_by_name: dict) -> str:
    """Resolve the actual parent PK column (relationship detector may emit 'id')."""
    if parent_col_hint.lower() != "id":
        return parent_col_hint
    parent_meta = tables_by_name.get(parent_table)
    if parent_meta:
        return _infer_pk(parent_table, parent_meta["columns"]) or parent_col_hint
    return parent_col_hint


# ---------------------------------------------------------------------------
# DDL builder
# ---------------------------------------------------------------------------


def generate_databricks_ddl(report: dict[str, Any], target_catalog: str | None = None) -> str:
    """
    Generate Databricks Unity Catalog DDL from a discovery report JSON.

    Produces:
      - CREATE TABLE IF NOT EXISTS with NOT NULL on PK/FK columns
      - NOT ENFORCED PRIMARY KEY constraints (inline)
      - NOT ENFORCED FOREIGN KEY constraints (ALTER TABLE, after creates)
      - USING DELTA + COMMENT
      - OPTIMIZE / ZORDER hints as comments
    """
    catalog = target_catalog or report.get("catalog", "target_catalog")
    schema = report.get("schema", "target_schema")
    tables = report.get("tables", [])
    relationships = report.get("relationships", [])

    tables_by_name = {t["name"]: t for t in tables}

    # Collect FKs per child table for inline awareness
    fk_columns: dict[str, set[str]] = {}
    for rel in relationships:
        child = rel["child_table"]
        fk_columns.setdefault(child, set()).add(rel["child_column"])

    # Collect inferred PKs
    pk_map: dict[str, str] = {}
    for t in tables:
        pk_col = t["primary_keys"][0] if t.get("primary_keys") else _infer_pk(t["name"], t["columns"])
        if pk_col:
            pk_map[t["name"]] = pk_col

    lines: list[str] = []

    lines.append("-- ============================================================")
    lines.append(f"-- Databricks DDL — {catalog}.{schema}")
    lines.append("-- Generated by Agentic Data Modeling (adm)")
    lines.append("-- Constraints are NOT ENFORCED (informational) per Databricks")
    lines.append("-- best-practice for optimizer hints and BI auto-join discovery.")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append(f"USE CATALOG `{catalog}`;")
    lines.append(f"USE SCHEMA `{schema}`;")
    lines.append("")

    # ---- CREATE TABLE statements -----------------------------------------
    for t in tables:
        tname = t["name"]
        cols = t["columns"]
        pk_col = pk_map.get(tname)
        fk_cols = fk_columns.get(tname, set())
        comment = t.get("comment") or f"{tname} table"

        lines.append("-- ------------------------------------------------------------")
        lines.append(f"-- {tname}")
        lines.append("-- ------------------------------------------------------------")
        lines.append(f"CREATE TABLE IF NOT EXISTS `{catalog}`.`{schema}`.`{tname}` (")

        col_defs = []
        for col in cols:
            col_name = col["name"]
            db_type = _map_type(col_name, col["type"])

            # NOT NULL on PK and FK columns (observed 0% nulls in source)
            is_key = (col_name == pk_col) or (col_name in fk_cols)
            nullability = "NOT NULL" if is_key else "NULL"

            # Escape column names with spaces or reserved words
            safe_name = f"`{col_name}`" if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", col_name) else col_name
            col_defs.append(f"    {safe_name:<30} {db_type:<20} {nullability}")

        # Inline PK constraint
        if pk_col:
            col_defs.append(f"    CONSTRAINT pk_{tname} PRIMARY KEY ({pk_col}) NOT ENFORCED")

        lines.append(",\n".join(col_defs))
        lines.append(")")
        lines.append("USING DELTA")
        lines.append(f"COMMENT '{comment}';")
        lines.append("")

    # ---- ALTER TABLE for FK constraints -----------------------------------
    lines.append("")
    lines.append("-- ============================================================")
    lines.append("-- Foreign Key Constraints (NOT ENFORCED — informational)")
    lines.append("-- ============================================================")
    lines.append("")

    for rel in relationships:
        child_table = rel["child_table"]
        child_col = rel["child_column"]
        parent_table = rel["parent_table"]
        parent_col = _resolve_parent_column(parent_table, rel["parent_column"], tables_by_name)
        conf = rel.get("confidence", 0)
        rel_type = rel.get("type", "inferred")

        constraint_name = f"fk_{child_table}_{child_col}_{parent_table}".lower()
        lines.append(f"-- [{rel_type}] confidence={conf:.0%}")
        lines.append(f"ALTER TABLE `{catalog}`.`{schema}`.`{child_table}`")
        lines.append(f"  ADD CONSTRAINT {constraint_name}")
        lines.append(f"  FOREIGN KEY ({child_col})")
        lines.append(f"  REFERENCES `{catalog}`.`{schema}`.`{parent_table}` ({parent_col})")
        lines.append("  NOT ENFORCED;")
        lines.append("")

    # ---- NOT NULL enforcement via ALTER -----------------------------------
    lines.append("")
    lines.append("-- ============================================================")
    lines.append("-- Enforce NOT NULL on key columns (safe — 0% nulls observed)")
    lines.append("-- ============================================================")
    lines.append("")
    for tname, pk_col in pk_map.items():
        lines.append(f"ALTER TABLE `{catalog}`.`{schema}`.`{tname}` " f"ALTER COLUMN {pk_col} SET NOT NULL;")
    lines.append("")

    # ---- Optimization hints -----------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- OPTIMIZE / ZORDER hints (run after data load)")
    lines.append("-- ============================================================")
    lines.append("")
    for rel in relationships:
        child_table = rel["child_table"]
        child_col = rel["child_column"]
        lines.append(f"-- OPTIMIZE `{catalog}`.`{schema}`.`{child_table}` " f"ZORDER BY ({child_col});")

    lines.append("")
    lines.append("-- End of DDL")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Mermaid ER diagram
# ---------------------------------------------------------------------------

# Map source/Databricks types to compact Mermaid-friendly type tokens
_MERMAID_TYPE_MAP: dict[str, str] = {
    "bigint": "bigint",
    "int": "int",
    "integer": "int",
    "smallint": "int",
    "tinyint": "int",
    "long": "bigint",
    "double": "float",
    "float": "float",
    "decimal": "decimal",
    "numeric": "decimal",
    "string": "string",
    "varchar": "string",
    "char": "string",
    "text": "string",
    "boolean": "boolean",
    "bool": "boolean",
    "timestamp": "timestamp",
    "timestamp_ntz": "timestamp",
    "date": "date",
    "binary": "binary",
}


def _mermaid_type(raw_type: str) -> str:
    """Map a source/Databricks type string to a compact Mermaid-friendly token."""
    base = raw_type.lower().split("(")[0].strip()
    return _MERMAID_TYPE_MAP.get(base, raw_type.lower())


def _safe_entity(name: str) -> str:
    """Replace spaces/hyphens so Mermaid parses entity names correctly."""
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def generate_mermaid_er_diagram(report: dict[str, Any]) -> str:
    """Generate a Mermaid erDiagram from a discovery report.

    Returns a Markdown string containing:
    - A fenced ```mermaid erDiagram block (renders in GitHub, VS Code, mermaid.live)
    - A Tables summary table (name, column count, PK, FK counts)
    - A Relationships table (child/parent table+column, type, confidence)
    - An AI Analysis section (recommendations, data quality, logical model, physical model)
      rendered only when the report contains a parsed ai_analysis dict.
    """
    tables = report.get("tables", [])
    relationships = report.get("relationships", [])

    # Build lookup structures
    tables_by_name = {t["name"]: t for t in tables}
    pk_map: dict[str, str] = {}
    for t in tables:
        pk_col = t["primary_keys"][0] if t.get("primary_keys") else _infer_pk(t["name"], t["columns"])
        if pk_col:
            pk_map[t["name"]] = pk_col

    fk_columns: dict[str, set[str]] = {}
    for rel in relationships:
        fk_columns.setdefault(rel["child_table"], set()).add(rel["child_column"])

    lines: list[str] = []
    lines.append("# Entity-Relationship Diagram")
    lines.append("")
    lines.append(
        "> Generated by Agentic Data Modeling · " f"source: `{report.get('catalog', '')}.{report.get('schema', '')}`"
    )
    lines.append("")
    lines.append("```mermaid")
    lines.append("erDiagram")

    # ---- Entity definitions ------------------------------------------------
    for t in tables:
        tname = t["name"]
        entity = _safe_entity(tname)
        pk_col = pk_map.get(tname)
        fk_cols = fk_columns.get(tname, set())

        lines.append(f"    {entity} {{")
        for col in t["columns"]:
            col_name = col["name"]
            mtype = _mermaid_type(col["type"])
            # sanitise attribute name: no spaces allowed in Mermaid
            safe_attr = re.sub(r"\s+", "_", col_name)
            if col_name == pk_col:
                marker = "PK"
            elif col_name in fk_cols:
                marker = "FK"
            else:
                marker = ""
            annotation = f' "{marker}"' if marker else ""
            lines.append(f"        {mtype} {safe_attr}{annotation}")
        lines.append("    }")
        lines.append("")

    # ---- Relationships -----------------------------------------------------
    for rel in relationships:
        parent = _safe_entity(rel["parent_table"])
        child = _safe_entity(rel["child_table"])
        rel_type = rel.get("type", "inferred")
        conf = rel.get("confidence", 0)
        label = "has" if rel_type == "explicit_fk" else f"~{int(conf * 100)}%"
        # one parent to zero-or-more children (standard FK cardinality)
        lines.append(f'    {parent} ||--o{{ {child} : "{label}"')

    lines.append("```")
    lines.append("")

    # ---- Summary table -----------------------------------------------------
    lines.append("## Tables")
    lines.append("")
    lines.append("| Table | Columns | Primary Key | Relationships |")
    lines.append("|-------|---------|-------------|--------------|")
    for t in tables:
        tname = t["name"]
        ncols = len(t["columns"])
        pk = pk_map.get(tname, "—")
        fk_count = sum(1 for r in relationships if r["child_table"] == tname)
        ref_count = sum(1 for r in relationships if r["parent_table"] == tname)
        rels_str = f"{fk_count} FK out · {ref_count} referenced"
        lines.append(f"| `{tname}` | {ncols} | `{pk}` | {rels_str} |")
    lines.append("")

    # ---- Relationships table -----------------------------------------------
    if relationships:
        lines.append("## Relationships")
        lines.append("")
        lines.append("| Child Table | Column | Parent Table | Column | Type | Confidence |")
        lines.append("|-------------|--------|--------------|--------|------|-----------|")
        for rel in relationships:
            parent_col = _resolve_parent_column(rel["parent_table"], rel["parent_column"], tables_by_name)
            lines.append(
                f"| `{rel['child_table']}` | `{rel['child_column']}` "
                f"| `{rel['parent_table']}` | `{parent_col}` "
                f"| {rel.get('type', '—')} | {rel.get('confidence', 0):.0%} |"
            )
        lines.append("")

    # ---- AI analysis summary -----------------------------------------------
    ai = report.get("ai_analysis")
    if isinstance(ai, dict):
        lines.append("## AI Analysis")
        lines.append("")

        recommendations = ai.get("modeling_recommendations", [])
        if recommendations:
            lines.append("### Modeling Recommendations")
            lines.append("")
            for rec in recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        dq = ai.get("data_quality", [])
        if dq:
            lines.append("### Data Quality Findings")
            lines.append("")
            lines.append("| Table | Issue | Detail |")
            lines.append("|-------|-------|--------|")
            for finding in dq:
                tbl = finding.get("table", "—")
                issue = finding.get("issue_type", "—")
                detail = finding.get("detail", "—")
                lines.append(f"| `{tbl}` | {issue} | {detail} |")
            lines.append("")

        logical = ai.get("logical_model", {})
        subject_areas = logical.get("subject_areas", {})
        if subject_areas:
            lines.append("### Logical Model — Subject Areas")
            lines.append("")
            lines.append("| Subject Area | Tables |")
            lines.append("|---|---|")
            for area, tbl_list in subject_areas.items():
                tbls = ", ".join(f"`{t}`" for t in tbl_list) if isinstance(tbl_list, list) else str(tbl_list)
                lines.append(f"| {area} | {tbls} |")
            lines.append("")

        physical = ai.get("physical_model", {})
        denorms = physical.get("denormalizations", [])
        indexes = physical.get("recommended_indexes", [])
        if denorms or indexes:
            lines.append("### Physical Model")
            lines.append("")
            if denorms:
                lines.append("**Denormalization Suggestions:**")
                lines.append("")
                for d in denorms:
                    lines.append(f"- {d}")
                lines.append("")
            if indexes:
                lines.append("**Recommended Indexes:**")
                lines.append("")
                for idx in indexes:
                    lines.append(f"- {idx}")
                lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ERwin assessment
# ---------------------------------------------------------------------------


def erwin_assessment(report: dict[str, Any]) -> str:
    """Return a plain-text ERwin import readiness assessment."""
    tables = report.get("tables", [])
    rels = report.get("relationships", [])
    missing_pks = [t["name"] for t in tables if not t.get("primary_keys")]

    lines = [
        "ERwin Import Readiness",
        "=" * 50,
        "",
        "ERwin Data Modeler reverse-engineers from a SQL DDL file.",
        "The generated .sql file IS the correct ERwin input.",
        "",
        "Steps to import into ERwin:",
        "  1. Open ERwin Data Modeler",
        "  2. File → Reverse Engineer → From Script",
        "  3. Select database: 'Databricks' or 'Generic ANSI SQL'",
        "  4. Browse to the generated .sql file",
        "  5. ERwin reads CREATE TABLE + CONSTRAINT statements",
        "     and builds the ERD automatically.",
        "",
        "Current JSON coverage:",
        f"  Tables           : {len(tables)}",
        f"  Relationships    : {len(rels)}",
        f"  Tables w/o decl PK: {len(missing_pks)} ({', '.join(missing_pks) or 'none'})",
        "    → PKs are inferred by naming convention in the DDL",
        "",
        "Limitations of the JSON alone (why DDL is needed):",
        "  - ERwin cannot read the raw JSON directly",
        "  - ERwin needs CONSTRAINT syntax in the DDL",
        "  - The .sql file generated here contains all CREATE TABLE,",
        "    PRIMARY KEY (NOT ENFORCED), and FOREIGN KEY statements",
        "    that ERwin parses to reconstruct the entity-relationship diagram.",
        "",
        "Recommended ERwin target dialect: 'Databricks' (ERwin 2021+)",
        "Fallback: 'Generic ANSI SQL' (removes USING DELTA / NOT ENFORCED)",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def generate_from_file(
    report_path: str,
    target_catalog: str | None = None,
    output_sql: str | None = None,
    output_erwin_notes: str | None = None,
    output_mermaid: str | None = None,
) -> tuple[str, str, str]:
    """Read a discovery JSON report and write DDL + ERwin notes + Mermaid ER diagram files."""
    report = json.loads(Path(report_path).read_text())

    ddl = generate_databricks_ddl(report, target_catalog=target_catalog)
    notes = erwin_assessment(report)
    diagram = generate_mermaid_er_diagram(report)

    base = Path(report_path)
    sql_path = output_sql or str(base.with_suffix(".sql"))
    notes_path = output_erwin_notes or str(base.with_suffix(".erwin_notes.txt"))
    mermaid_path = output_mermaid or str(base.with_suffix(".er_diagram.md"))

    Path(sql_path).write_text(ddl)
    Path(notes_path).write_text(notes)
    Path(mermaid_path).write_text(diagram)

    return sql_path, notes_path, mermaid_path
